In [65]:
import pandas as pd

In [82]:
# comando para ler o arquivo
data = pd.read_csv (filepath_or_buffer ='C:/Users/Gabriel-PC/Bootcamp-Data-science/teste/aulas/2023.05.31 - aula Nopha/dataframe_python.csv')

In [83]:
# mostra o dataframe
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,{'S': 'Analista de Recursos Humanos'},{'N': '77'},"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",{'BOOL': False},{'BOOL': False}
1,{'S': 'Diretor de Recursos Humanos'},{'N': '51'},"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
2,{'S': 'Diretor Executivo'},{'N': '49'},"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",{'BOOL': False},{'BOOL': False}
3,{'S': 'CEO Chief Executive Officer'},{'N': '64'},"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
4,{'S': 'Auxiliar Administrativo'},{'N': '70'},"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
...,...,...,...,...,...,...
1550,{'S': 'Analista de Sistemas'},{'N': '0'},"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",{'BOOL': False},{'BOOL': True}
1551,{'S': 'Coordenador de Desenvolvimento'},{'N': '44'},"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}
1552,{'S': 'Analista de Recursos Humanos'},{'N': '74'},"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
1553,{'S': 'Gerente de Recursos Humanos'},{'N': '44'},"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
1554,{'S': 'Analista de Recursos Humanos'},{'N': '83'},"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}

In [84]:
# passa pelo dataframe lendo linha a linha

# for index, row in data.iterrows() :
#     role = eval(row['role'])
#     # print(index, row)
#     print(role)

In [85]:
# serie = list(data['role'])

In [86]:
#tratando coluna 'role'

def tratamento_coluna (data: pd.DataFrame, serie:str, get:str) :
    
    series = list(data[serie])
    new_list = list()
    for elem in series :
        new_list.append(eval(elem).get(get))
    data[serie] = new_list

    return data

In [87]:
data = tratamento_coluna (data=data, serie='role', get='S')

In [88]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,Analista de Recursos Humanos,{'N': '77'},"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",{'BOOL': False},{'BOOL': False}
1,Diretor de Recursos Humanos,{'N': '51'},"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
2,Diretor Executivo,{'N': '49'},"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",{'BOOL': False},{'BOOL': False}
3,CEO Chief Executive Officer,{'N': '64'},"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
4,Auxiliar Administrativo,{'N': '70'},"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
...,...,...,...,...,...,...
1550,Analista de Sistemas,{'N': '0'},"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",{'BOOL': False},{'BOOL': True}
1551,Coordenador de Desenvolvimento,{'N': '44'},"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}
1552,Analista de Recursos Humanos,{'N': '74'},"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
1553,Gerente de Recursos Humanos,{'N': '44'},"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
1554,Analista de Recursos Humanos,{'N': '83'},"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}

In [89]:
data = tratamento_coluna(data=data, serie='fit', get='N')

In [90]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,Analista de Recursos Humanos,77,"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",{'BOOL': False},{'BOOL': False}
1,Diretor de Recursos Humanos,51,"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
2,Diretor Executivo,49,"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",{'BOOL': False},{'BOOL': False}
3,CEO Chief Executive Officer,64,"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
4,Auxiliar Administrativo,70,"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
...,...,...,...,...,...,...
1550,Analista de Sistemas,0,"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",{'BOOL': False},{'BOOL': True}
1551,Coordenador de Desenvolvimento,44,"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}
1552,Analista de Recursos Humanos,74,"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
1553,Gerente de Recursos Humanos,44,"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
1554,Analista de Recursos Humanos,83,"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}

In [91]:
data = tratamento_coluna(data=data, serie='compressed', get='BOOL')

In [92]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,Analista de Recursos Humanos,77,"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",False,{'BOOL': False}
1,Diretor de Recursos Humanos,51,"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",False,{'BOOL': False}
2,Diretor Executivo,49,"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",False,{'BOOL': False}
3,CEO Chief Executive Officer,64,"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",False,{'BOOL': False}
4,Auxiliar Administrativo,70,"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",False,{'BOOL': False}
...,...,...,...,...,...,...
1550,Analista de Sistemas,0,"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",False,{'BOOL': True}
1551,Coordenador de Desenvolvimento,44,"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",False,{'BOOL': False}
1552,Analista de Recursos Humanos,74,"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",False,{'BOOL': False}
1553,Gerente de Recursos Humanos,44,"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",False,{'BOOL': False}
1554,Analista de Recursos Humanos,83,"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",False,{'BOOL': False}

In [93]:
data = tratamento_coluna(data=data, serie='over_time', get='BOOL')

In [94]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,Analista de Recursos Humanos,77,"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",False,False
1,Diretor de Recursos Humanos,51,"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",False,False
2,Diretor Executivo,49,"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",False,False
3,CEO Chief Executive Officer,64,"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",False,False
4,Auxiliar Administrativo,70,"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",False,False
...,...,...,...,...,...,...
1550,Analista de Sistemas,0,"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",False,True
1551,Coordenador de Desenvolvimento,44,"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",False,False
1552,Analista de Recursos Humanos,74,"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",False,False
1553,Gerente de Recursos Humanos,44,"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",False,False
1554,Analista de Recursos Humanos,83,"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",False,False