In [1]:
import pandas as pd

In [2]:
# comando para ler o arquivo
data = pd.read_csv (filepath_or_buffer ='C:/Users/Gabriel-PC/Bootcamp-Data-science/teste/aulas/2023.05.31 - aula Nopha/dataframe_python.csv')

In [3]:
# mostra o dataframe
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,{'S': 'Analista de Recursos Humanos'},{'N': '77'},"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",{'BOOL': False},{'BOOL': False}
1,{'S': 'Diretor de Recursos Humanos'},{'N': '51'},"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
2,{'S': 'Diretor Executivo'},{'N': '49'},"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",{'BOOL': False},{'BOOL': False}
3,{'S': 'CEO Chief Executive Officer'},{'N': '64'},"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
4,{'S': 'Auxiliar Administrativo'},{'N': '70'},"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
...,...,...,...,...,...,...
1550,{'S': 'Analista de Sistemas'},{'N': '0'},"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",{'BOOL': False},{'BOOL': True}
1551,{'S': 'Coordenador de Desenvolvimento'},{'N': '44'},"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}
1552,{'S': 'Analista de Recursos Humanos'},{'N': '74'},"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
1553,{'S': 'Gerente de Recursos Humanos'},{'N': '44'},"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
1554,{'S': 'Analista de Recursos Humanos'},{'N': '83'},"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}

In [4]:
# passa pelo dataframe lendo linha a linha

# for index, row in data.iterrows() :
#     role = eval(row['role'])
#     # print(index, row)
#     print(role)

In [5]:
# serie = list(data['role'])

In [6]:
#tratando coluna 'role'

def tratamento_coluna (data: pd.DataFrame, serie:str, get:str) :
    
    series = list(data[serie])
    new_list = list()
    for elem in series :
        new_list.append(eval(elem).get(get))
    data[serie] = new_list

    return data

In [7]:
data = tratamento_coluna (data=data, serie='role', get='S')

In [8]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,Analista de Recursos Humanos,{'N': '77'},"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",{'BOOL': False},{'BOOL': False}
1,Diretor de Recursos Humanos,{'N': '51'},"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
2,Diretor Executivo,{'N': '49'},"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",{'BOOL': False},{'BOOL': False}
3,CEO Chief Executive Officer,{'N': '64'},"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
4,Auxiliar Administrativo,{'N': '70'},"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
...,...,...,...,...,...,...
1550,Analista de Sistemas,{'N': '0'},"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",{'BOOL': False},{'BOOL': True}
1551,Coordenador de Desenvolvimento,{'N': '44'},"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}
1552,Analista de Recursos Humanos,{'N': '74'},"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
1553,Gerente de Recursos Humanos,{'N': '44'},"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
1554,Analista de Recursos Humanos,{'N': '83'},"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}

In [9]:
data = tratamento_coluna(data=data, serie='fit', get='N')

In [10]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,Analista de Recursos Humanos,77,"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",{'BOOL': False},{'BOOL': False}
1,Diretor de Recursos Humanos,51,"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
2,Diretor Executivo,49,"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",{'BOOL': False},{'BOOL': False}
3,CEO Chief Executive Officer,64,"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
4,Auxiliar Administrativo,70,"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
...,...,...,...,...,...,...
1550,Analista de Sistemas,0,"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",{'BOOL': False},{'BOOL': True}
1551,Coordenador de Desenvolvimento,44,"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}
1552,Analista de Recursos Humanos,74,"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",{'BOOL': False},{'BOOL': False}
1553,Gerente de Recursos Humanos,44,"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",{'BOOL': False},{'BOOL': False}
1554,Analista de Recursos Humanos,83,"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",{'BOOL': False},{'BOOL': False}

In [11]:
data = tratamento_coluna(data=data, serie='compressed', get='BOOL')

In [12]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,Analista de Recursos Humanos,77,"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",False,{'BOOL': False}
1,Diretor de Recursos Humanos,51,"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",False,{'BOOL': False}
2,Diretor Executivo,49,"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",False,{'BOOL': False}
3,CEO Chief Executive Officer,64,"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",False,{'BOOL': False}
4,Auxiliar Administrativo,70,"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",False,{'BOOL': False}
...,...,...,...,...,...,...
1550,Analista de Sistemas,0,"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",False,{'BOOL': True}
1551,Coordenador de Desenvolvimento,44,"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",False,{'BOOL': False}
1552,Analista de Recursos Humanos,74,"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",False,{'BOOL': False}
1553,Gerente de Recursos Humanos,44,"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",False,{'BOOL': False}
1554,Analista de Recursos Humanos,83,"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",False,{'BOOL': False}

In [13]:
data = tratamento_coluna(data=data, serie='over_time', get='BOOL')

In [14]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time
0,Analista de Recursos Humanos,77,"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",False,False
1,Diretor de Recursos Humanos,51,"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",False,False
2,Diretor Executivo,49,"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",False,False
3,CEO Chief Executive Officer,64,"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",False,False
4,Auxiliar Administrativo,70,"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",False,False
...,...,...,...,...,...,...
1550,Analista de Sistemas,0,"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",False,True
1551,Coordenador de Desenvolvimento,44,"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",False,False
1552,Analista de Recursos Humanos,74,"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",False,False
1553,Gerente de Recursos Humanos,44,"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",False,False
1554,Analista de Recursos Humanos,83,"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",False,False

In [15]:
series = data["natural_percentage"].apply( lambda x: eval(x))

In [16]:
dic = {
    "F" : [],
    "L" : [],
    "O" : [],
    "W" : []
}
for line in list(series) : 
    list_ = line["S"]
    dict_ = eval(list_)[0]

    for key, values in dict_.items() :
        dic[key].append(values)
    
for key, value in dic.items() :
    data[f"natural_{key.lower()}"] = value

In [17]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time,natural_f,natural_l,natural_o,natural_w
0,Analista de Recursos Humanos,77,"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",False,False,45,74,88,48
1,Diretor de Recursos Humanos,51,"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",False,False,88,22,44,64
2,Diretor Executivo,49,"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",False,False,32,87,67,64
3,CEO Chief Executive Officer,64,"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",False,False,88,45,52,48
4,Auxiliar Administrativo,70,"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",False,False,54,22,58,79
...,...,...,...,...,...,...,...,...,...,...
1550,Analista de Sistemas,0,"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",False,True,50,50,50,50
1551,Coordenador de Desenvolvimento,44,"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",False,False,60,95,25,43
1552,Analista de Recursos Humanos,74,"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",False,False,45,95,44,43
1553,Gerente de Recursos Humanos,44,"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",False,False,17,95,88,79
1554,Analista de Recursos Humanos,83,"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",False,False,43,74,67,59

In [18]:
series = data["adapted_percentage"].apply( lambda x: eval(x))

In [19]:
dic = {
    "F" : [],
    "L" : [],
    "O" : [],
    "W" : []
}
for line in list(series) : 
    list_ = line["S"]
    dict_ = eval(list_)[0]

    for key, values in dict_.items() :
        dic[key].append(values)
    
for key, value in dic.items() :
    data[f"adapted_{key.lower()}"] = value

In [20]:
data

,role,fit,natural_percentage,adapted_percentage,compressed,over_time,natural_f,natural_l,natural_o,natural_w,adapted_f,adapted_l,adapted_o,adapted_w
0,Analista de Recursos Humanos,77,"{'S': '[{""F"": 45, ""L"": 74, ""O"": 88, ""W"": 48}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 65}]'}",False,False,45,74,88,48,37,86,41,65
1,Diretor de Recursos Humanos,51,"{'S': '[{""F"": 88, ""L"": 22, ""O"": 44, ""W"": 64}]'}","{'S': '[{""F"": 88, ""L"": 29, ""O"": 30, ""W"": 43}]'}",False,False,88,22,44,64,88,29,30,43
2,Diretor Executivo,49,"{'S': '[{""F"": 32, ""L"": 87, ""O"": 67, ""W"": 64}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 53, ""W"": 29}]'}",False,False,32,87,67,64,32,81,53,29
3,CEO Chief Executive Officer,64,"{'S': '[{""F"": 88, ""L"": 45, ""O"": 52, ""W"": 48}]'}","{'S': '[{""F"": 69, ""L"": 75, ""O"": 20, ""W"": 43}]'}",False,False,88,45,52,48,69,75,20,43
4,Auxiliar Administrativo,70,"{'S': '[{""F"": 54, ""L"": 22, ""O"": 58, ""W"": 79}]'}","{'S': '[{""F"": 47, ""L"": 50, ""O"": 46, ""W"": 73}]'}",False,False,54,22,58,79,47,50,46,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,Analista de Sistemas,0,"{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}","{'S': '[{""F"": 50, ""L"": 50, ""O"": 50, ""W"": 50}]'}",False,True,50,50,50,50,50,50,50,50
1551,Coordenador de Desenvolvimento,44,"{'S': '[{""F"": 60, ""L"": 95, ""O"": 25, ""W"": 43}]'}","{'S': '[{""F"": 37, ""L"": 86, ""O"": 41, ""W"": 53}]'}",False,False,60,95,25,43,37,86,41,53
1552,Analista de Recursos Humanos,74,"{'S': '[{""F"": 45, ""L"": 95, ""O"": 44, ""W"": 43}]'}","{'S': '[{""F"": 32, ""L"": 81, ""O"": 59, ""W"": 43}]'}",False,False,45,95,44,43,32,81,59,43
1553,Gerente de Recursos Humanos,44,"{'S': '[{""F"": 17, ""L"": 95, ""O"": 88, ""W"": 79}]'}","{'S': '[{""F"": 25, ""L"": 67, ""O"": 72, ""W"": 73}]'}",False,False,17,95,88,79,25,67,72,73
1554,Analista de Recursos Humanos,83,"{'S': '[{""F"": 43, ""L"": 74, ""O"": 67, ""W"": 59}]'}","{'S': '[{""F"": 62, ""L"": 39, ""O"": 53, ""W"": 53}]'}",False,False,43,74,67,59,62,39,53,53

: